import type { Metadata } from 'next';

// These styles apply to every route in the application
import './globals.css';
import { Providers } from './provider';
import NavMenu from '@/components/shared/NavMenu';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body>
        <NavMenu />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
